# Generated by Django 3.0.4 on 2020-10-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20201025_1434'),
        ('users', '0002_auto_20201023_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tickets',
            field=models.ManyToManyField(through='tickets.UserTicket', to='tickets.Ticket'),
        ),
    ]
