# Generated by Django 3.0.4 on 2020-10-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('name', 'event_date')},
        ),
        migrations.RemoveField(
            model_name='event',
            name='total_seats',
        ),
    ]
