# Generated by Django 3.0.4 on 2020-10-25 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0003_auto_20201024_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userticket',
            name='status',
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('canceled', 'Canceled'), ('booked', 'Booked'), ('unpaid', 'Unpaid')], default='booked', max_length=15),
        ),
        migrations.AlterField(
            model_name='userticket',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userticket',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Ticket'),
        ),
    ]
