# Generated by Django 3.0.4 on 2020-10-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20201025_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('canceled', 'Canceled'), ('booked', 'Booked'), ('unpaid', 'Unpaid'), ('spare', 'Spare')], default='spare', max_length=15),
        ),
    ]
