# Generated by Django 3.0.4 on 2020-10-25 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20201025_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userticket',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.Ticket'),
        ),
    ]
