# Generated by Django 3.0.4 on 2020-10-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20201025_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('booked', 'Booked'), ('spare', 'Spare')], default='spare', max_length=10),
        ),
    ]
